name = "skyxing"
main = "src/index.js"
compatibility_date = "2026-01-01"
workers_dev = true

[[kv_namespaces]]
binding = "SKYXING_KV"
id = "73f13dd572bc4ee58dc6946933568b9e"
preview_id = "73f13dd572bc4ee58dc6946933568b9e"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "none"

# 明文环境变量（非机密）
[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAAD5wIJ0zrusozG2N"
